const SEED_TOPICS = [
  {
    "createdAt": 1748000000000,
    "enabled": true,
    "icon": "🎵",
    "id": "music_songs",
    "keywords": [
      "new hindi song 2026",
      "bollywood songs 2026",
      "arijit singh new song",
      "AP Dhillon",
      "Diljit Dosanjh new song",
      "punjabi song 2026",
      "4k video song",
      "unplugged hindi cover",
      "lofi hindi mix",
      "marathi songs new",
      "tamil songs new",
      "telugu songs new",
      "kannada new song",
      "bhojpuri new song",
      "K-pop music video",
      "J-pop music video",
      "latin music video",
      "afrobeats music video",
      "arabic pop song",
      "turkish pop song",
      "NPR tiny desk concert",
      "Colors show performance",
      "live concert 4k",
      "acoustic session",
      "one take music video",
      "music producer making beat",
      "vocal coach reaction",
      "classical fusion indian"
    ],
    "name": "Music & Songs",
    "position": 0
  },
  {
    "createdAt": 1748000000001,
    "enabled": true,
    "icon": "🎬",
    "id": "bollywood_cinema",
    "keywords": [
      "bollywood trailer 2026",
      "new hindi movie 2026",
      "movie review hindi",
      "ott releases this week",
      "web series hindi review",
      "bollywood explained hindi",
      "netflix india new",
      "amazon prime india",
      "top 10 hindi movies",
      "film explained hindi",
      "south indian movie hindi dubbed",
      "tollywood new movie",
      "korean drama hindi",
      "anime hindi dubbed",
      "oscar winning movie review",
      "imdb top rated movie review",
      "hollywood movie explained hindi",
      "thriller movie explained hindi",
      "horror movie explained hindi",
      "documentary film 2026"
    ],
    "name": "Bollywood & OTT",
    "position": 1
  },
  {
    "createdAt": 1748000000002,
    "enabled": true,
    "icon": "🌿",
    "id": "nature_4k",
    "keywords": [
      "4k nature relaxation",
      "8k ultra hd nature",
      "12k nature video",
      "dolby vision nature",
      "hdr nature 4k",
      "relaxing nature sounds",
      "cozy rain ambience",
      "waterfall 4k",
      "forest sounds birds",
      "beautiful places earth 4k",
      "drone nature footage",
      "northern lights 4k",
      "thunderstorm ambience",
      "ocean waves 4k",
      "snowfall ambience 4k",
      "fireplace crackling",
      "river sounds sleep",
      "ambient nature no music",
      "japanese garden 4k",
      "cherry blossom 4k",
      "autumn forest 4k",
      "desert landscape 4k",
      "mountain scenery 4k"
    ],
    "name": "4K Nature & Ambience",
    "position": 2
  },
  {
    "createdAt": 1748000000003,
    "enabled": true,
    "icon": "🌏",
    "id": "city_walk",
    "keywords": [
      "tokyo walk 4k",
      "osaka night walk",
      "kyoto walk 4k",
      "seoul walk 4k",
      "shanghai walk 4k",
      "hong kong walk",
      "singapore walk 4k",
      "bangkok walk 4k",
      "dubai walk 4k",
      "istanbul walk 4k",
      "london walk 4k",
      "paris walk 4k",
      "rome walk 4k",
      "amsterdam walk 4k",
      "prague walk 4k",
      "barcelona walk 4k",
      "new york city walk 4k",
      "los angeles walk 4k",
      "mumbai walk 4k",
      "delhi walk 4k",
      "varanasi walk 4k",
      "rain walk 4k",
      "night city walk hdr",
      "christmas market walk",
      "old town walk europe",
      "night market walk asia",
      "virtual tour museum",
      "ancient ruins tour 4k"
    ],
    "name": "City Walks & Sightseeing",
    "position": 3
  },
  {
    "createdAt": 1748000000004,
    "enabled": true,
    "icon": "🍔",
    "id": "food_street",
    "keywords": [
      "indian street food",
      "mumbai street food",
      "delhi street food",
      "nagpur food",
      "pune street food",
      "hyderabadi biryani making",
      "south indian food tour",
      "kolkata street food",
      "lucknow food tour",
      "korean street food",
      "japanese street food",
      "tokyo food tour",
      "osaka food tour",
      "thai street food bangkok",
      "turkish street food istanbul",
      "mexican street food",
      "italian food tour rome",
      "chinese street food",
      "taiwan night market food",
      "vietnamese street food",
      "moroccan street food",
      "peruvian food tour",
      "mukbang",
      "food challenge",
      "village cooking",
      "traditional cooking",
      "biggest food ever",
      "food factory tour",
      "how it's made food",
      "best restaurant review"
    ],
    "name": "Global Street Food",
    "position": 4
  },
  {
    "createdAt": 1748000000005,
    "enabled": true,
    "icon": "😂",
    "id": "comedy_pranks",
    "keywords": [
      "stand up comedy hindi",
      "stand up comedy english",
      "kapil sharma show",
      "try not to laugh",
      "funny video compilation 2026",
      "prank video india",
      "meme compilation 2026",
      "reaction video funny",
      "daily dose of internet",
      "failarmy",
      "college comedy india",
      "marathi comedy",
      "comedy sketch",
      "improv comedy",
      "roast battle",
      "dark humor compilation",
      "anime funny moments",
      "best of reddit stories",
      "comedians carpool karaoke"
    ],
    "name": "Comedy & Pranks",
    "position": 5
  },
  {
    "createdAt": 1748000000006,
    "enabled": true,
    "icon": "🐾",
    "id": "animals_wildlife",
    "keywords": [
      "wildlife documentary 4k",
      "BBC earth documentary",
      "national geographic animals",
      "planet earth documentary",
      "lion pride documentary",
      "tiger in wild india",
      "african safari wildlife",
      "deep sea creatures documentary",
      "cute baby animals compilation",
      "funny dogs compilation",
      "funny cats compilation",
      "animal rescue",
      "rare animals discovered",
      "bear encounter wild",
      "shark documentary",
      "whale documentary",
      "bird watching 4k",
      "insect macro 4k",
      "underwater world 4k",
      "animal intelligence documentary",
      "wolf pack documentary",
      "crocodile hunting documentary",
      "pets funny moments"
    ],
    "name": "Animals & Wildlife",
    "position": 6
  },
  {
    "createdAt": 1748000000007,
    "enabled": true,
    "icon": "🔬",
    "id": "space_science",
    "keywords": [
      "space documentary 4k",
      "james webb telescope 2026",
      "black hole documentary",
      "universe documentary",
      "spacex launch 2026",
      "mars exploration 2026",
      "solar system 4k",
      "quantum physics explained",
      "Kurzgesagt",
      "Veritasium",
      "SmarterEveryDay",
      "science explained hindi",
      "evolution documentary",
      "deep sea exploration",
      "volcano eruption documentary",
      "dinosaur documentary",
      "nuclear fusion 2026",
      "CRISPR gene editing",
      "brain science documentary",
      "ocean science documentary",
      "new discovery 2026",
      "archaeological discovery 2026",
      "nanotechnology documentary",
      "physics documentary"
    ],
    "name": "Science & Discoveries",
    "position": 7
  },
  {
    "createdAt": 1748000000008,
    "enabled": true,
    "icon": "📱",
    "id": "tech_gadgets",
    "keywords": [
      "smartphone review 2026",
      "best phone 2026",
      "iphone 17 review",
      "samsung galaxy review",
      "pixel review 2026",
      "budget phone under 20000",
      "foldable phone 2026",
      "laptop review 2026",
      "macbook review",
      "gaming laptop 2026",
      "gaming pc build 2026",
      "earbuds review 2026",
      "smartwatch review",
      "camera review 2026",
      "drone review 2026",
      "GPU review 2026",
      "VR headset review",
      "apple vision pro review",
      "smart home setup tour",
      "gaming setup tour",
      "mechanical keyboard review",
      "monitor review 4k",
      "electric vehicle review 2026",
      "best gadgets 2026",
      "tech news today",
      "MKBHD",
      "Linus tech tips",
      "tech unboxing",
      "tech deals 2026"
    ],
    "name": "Tech & Gadgets",
    "position": 8
  },
  {
    "createdAt": 1748000000009,
    "enabled": true,
    "icon": "🤖",
    "id": "ai_future",
    "keywords": [
      "artificial intelligence 2026",
      "ChatGPT new features",
      "Google Gemini 2026",
      "Claude AI",
      "AI tools 2026",
      "AI video generation",
      "AI music generation",
      "humanoid robot 2026",
      "AI news today",
      "machine learning tutorial",
      "open source AI model",
      "local AI setup",
      "AI coding assistant",
      "AI replaces jobs 2026",
      "future technology 2026",
      "robotics 2026",
      "autonomous driving 2026",
      "neural interface brain",
      "AGI artificial general intelligence",
      "AI documentary"
    ],
    "name": "AI & Future Tech",
    "position": 9
  },
  {
    "createdAt": 1748000000010,
    "enabled": true,
    "icon": "💪",
    "id": "health_fitness",
    "keywords": [
      "home workout no equipment",
      "gym workout routine",
      "yoga for beginners",
      "weight loss journey",
      "diet plan hindi",
      "dr berg",
      "fitness motivation",
      "meditation guided",
      "mental health documentary",
      "ayurveda tips hindi",
      "intermittent fasting results",
      "calisthenics workout",
      "running tips beginners",
      "stretching routine",
      "bodybuilding documentary",
      "martial arts training",
      "boxing workout",
      "sleep science documentary",
      "cold plunge benefits",
      "longevity science"
    ],
    "name": "Health & Fitness",
    "position": 10
  },
  {
    "createdAt": 1748000000011,
    "enabled": true,
    "icon": "💰",
    "id": "finance_money",
    "keywords": [
      "stock market hindi 2026",
      "mutual funds beginners hindi",
      "crypto news 2026",
      "financial planning hindi",
      "passive income ideas india",
      "make money online 2026",
      "share market basics hindi",
      "nifty sensex analysis",
      "real estate india 2026",
      "gold investment 2026",
      "side hustle ideas",
      "business ideas india",
      "startup story india",
      "wealth building strategy",
      "tax saving india 2026",
      "SIP investment guide",
      "personal finance documentary",
      "billionaire documentary",
      "economics explained",
      "recession 2026"
    ],
    "name": "Finance & Investing",
    "position": 11
  },
  {
    "createdAt": 1748000000012,
    "enabled": true,
    "icon": "🎮",
    "id": "gaming",
    "keywords": [
      "GTA 6 gameplay",
      "minecraft 2026",
      "new game release 2026",
      "gaming highlights compilation",
      "esports tournament 2026",
      "valorant highlights",
      "call of duty gameplay",
      "bgmi highlights",
      "pubg mobile gameplay",
      "roblox gameplay",
      "fortnite gameplay",
      "elden ring gameplay",
      "horror game gameplay",
      "indie game review",
      "retro gaming",
      "game review 2026",
      "gaming montage",
      "speedrun world record",
      "VR gaming",
      "ps5 exclusive 2026"
    ],
    "name": "Gaming",
    "position": 12
  },
  {
    "createdAt": 1748000000013,
    "enabled": true,
    "icon": "🕵️",
    "id": "true_crime",
    "keywords": [
      "true crime documentary",
      "murder mystery documentary",
      "unsolved mystery",
      "cold case solved 2026",
      "crime story hindi",
      "criminal psychology documentary",
      "heist documentary",
      "spy documentary",
      "serial killer documentary",
      "disappearance mystery",
      "forensic science documentary",
      "prison documentary",
      "drug cartel documentary",
      "mafia documentary",
      "conspiracy theory debunked",
      "supernatural mystery hindi",
      "haunted places documentary",
      "cult documentary",
      "scam documentary",
      "wrongful conviction documentary"
    ],
    "name": "True Crime & Mystery",
    "position": 13
  },
  {
    "createdAt": 1748000000014,
    "enabled": true,
    "icon": "🛠️",
    "id": "diy_maker",
    "keywords": [
      "woodworking project",
      "furniture making",
      "metalworking project",
      "blacksmithing",
      "arduino project 2026",
      "raspberry pi project",
      "3d printing project",
      "car restoration timelapse",
      "engine rebuild",
      "watch restoration",
      "primitive technology",
      "bushcraft shelter build",
      "tiny house build",
      "off grid cabin build",
      "container house build",
      "swimming pool build DIY",
      "pottery making",
      "leather craft",
      "resin art epoxy",
      "knife making",
      "home renovation timelapse",
      "hydroponic garden setup",
      "solar panel installation DIY",
      "drone build fpv",
      "jugaad india invention"
    ],
    "name": "DIY & Making",
    "position": 14
  },
  {
    "createdAt": 1748000000015,
    "enabled": true,
    "icon": "🧭",
    "id": "adventure_outdoors",
    "keywords": [
      "trekking himalayas",
      "road trip india",
      "camping india",
      "solo travel india vlog",
      "bike trip ladakh",
      "paragliding india",
      "overlanding africa",
      "adventure motorcycle trip",
      "backpacking europe",
      "backpacking southeast asia",
      "amazon jungle expedition",
      "african safari",
      "antarctica expedition",
      "iceland adventure",
      "norway fjords",
      "new zealand adventure",
      "skydiving",
      "base jumping",
      "free solo climbing",
      "deep sea diving",
      "cave exploration",
      "white water rafting",
      "van life adventure",
      "wilderness survival",
      "off grid living",
      "sailing around world"
    ],
    "name": "Adventure & Exploration",
    "position": 15
  },
  {
    "createdAt": 1748000000016,
    "enabled": true,
    "icon": "🌍",
    "id": "world_news",
    "keywords": [
      "world news today",
      "india news hindi",
      "geopolitics explained",
      "military documentary",
      "war documentary",
      "india china news",
      "us politics 2026",
      "economic crisis 2026",
      "current affairs hindi",
      "nato news 2026",
      "climate change documentary",
      "immigration documentary",
      "investigation journalism",
      "vice documentary",
      "Al Jazeera documentary",
      "DW documentary"
    ],
    "name": "World News & Geopolitics",
    "position": 16
  },
  {
    "createdAt": 1748000000017,
    "enabled": true,
    "icon": "🎭",
    "id": "marathi_entertainment",
    "keywords": [
      "hasyajatra 2026",
      "sony marathi",
      "zee marathi new",
      "marathi comedy natak",
      "marathi movie 2026",
      "marathi lavani dance",
      "marathi stand up comedy",
      "marathi vlog",
      "marathi food vlog",
      "pune marathi vlog",
      "nashik marathi vlog",
      "kokan marathi vlog",
      "marathi serial 2026",
      "marathi song 2026",
      "maharashtra documentary"
    ],
    "name": "Marathi Entertainment",
    "position": 17
  },
  {
    "createdAt": 1748000000018,
    "enabled": true,
    "icon": "✨",
    "id": "spirituality_motivation",
    "keywords": [
      "acharya prashant latest",
      "sandeep maheshwari",
      "sadhguru latest",
      "bk shivani",
      "osho hindi",
      "motivation hindi",
      "stoicism explained",
      "mindfulness meditation",
      "morning motivation",
      "success story hindi",
      "monk mindset",
      "philosophy explained",
      "marcus aurelius",
      "naval ravikant wisdom",
      "self improvement documentary",
      "TED talk motivation",
      "discipline motivation",
      "positive thinking hindi"
    ],
    "name": "Spirituality & Motivation",
    "position": 18
  },
  {
    "createdAt": 1748000000019,
    "enabled": true,
    "icon": "🏏",
    "id": "cricket_sports",
    "keywords": [
      "ipl 2026 highlights",
      "india cricket highlights",
      "t20 world cup",
      "virat kohli",
      "dhoni best moments",
      "cricket analysis hindi",
      "india vs pakistan cricket",
      "premier league highlights",
      "champions league highlights",
      "NBA highlights",
      "UFC fight highlights",
      "F1 race highlights",
      "Olympics 2026",
      "wrestling highlights wwe",
      "tennis highlights",
      "boxing fight highlights",
      "sports documentary",
      "athlete documentary",
      "pro kabaddi highlights",
      "sports fails compilation"
    ],
    "name": "Cricket & Sports",
    "position": 19
  },
  {
    "createdAt": 1748000000020,
    "enabled": true,
    "icon": "🔍",
    "id": "metal_detector",
    "keywords": [
      "metal detector finds 2026",
      "treasure hunting underwater",
      "buried treasure found",
      "river treasure hunting",
      "gold nugget found",
      "old coins found metal detecting",
      "shipwreck treasure discovery",
      "ancient artifact found",
      "magnet fishing finds",
      "storage unit auction finds",
      "antique roadshow rare find",
      "gem mining discovery"
    ],
    "name": "Treasure Hunting",
    "position": 20
  },
  {
    "createdAt": 1748000000021,
    "enabled": true,
    "icon": "🏖️",
    "id": "beach_ocean",
    "keywords": [
      "beach walk 4k",
      "ocean documentary 4k",
      "coral reef 4k underwater",
      "ocean sounds 4k",
      "surfing highlights",
      "deep sea documentary",
      "whale watching 4k",
      "shark diving 4k",
      "snorkeling 4k",
      "maldives 4k",
      "caribbean beach 4k",
      "bora bora 4k",
      "great barrier reef 4k",
      "fishing big catch",
      "deep sea fishing",
      "submarine documentary"
    ],
    "name": "Beach & Ocean",
    "position": 21
  },
  {
    "createdAt": 1748000000022,
    "enabled": true,
    "icon": "🏠",
    "id": "home_interior",
    "keywords": [
      "home renovation timelapse",
      "interior design ideas 2026",
      "small house design india",
      "apartment tour luxury",
      "home decor budget india",
      "smart home setup 2026",
      "modular kitchen design",
      "bedroom makeover",
      "bathroom renovation",
      "tiny house tour",
      "million dollar home tour",
      "japanese interior design",
      "scandinavian interior",
      "minimalist home tour",
      "garden makeover",
      "before after renovation"
    ],
    "name": "Home & Interior",
    "position": 22
  },
  {
    "createdAt": 1748000000023,
    "enabled": true,
    "icon": "🚗",
    "id": "cars_bikes",
    "keywords": [
      "car review 2026 india",
      "new car launch india 2026",
      "electric car review 2026",
      "superbike review",
      "supercar review",
      "car modification india",
      "royal enfield review",
      "road test hindi",
      "car vs car comparison",
      "formula 1 car",
      "hypercar review",
      "car restoration project",
      "muscle car review",
      "off road adventure car",
      "electric scooter review 2026",
      "top speed test car",
      "crash test car",
      "auto detailing",
      "car camping setup"
    ],
    "name": "Cars & Bikes",
    "position": 23
  },
  {
    "createdAt": 1748000000024,
    "enabled": true,
    "icon": "📚",
    "id": "education_facts",
    "keywords": [
      "amazing facts hindi",
      "did you know facts",
      "history documentary hindi",
      "world history documentary",
      "ancient civilization documentary",
      "psychology facts explained",
      "mythology hindi",
      "Egyptian mythology",
      "Greek mythology",
      "Norse mythology",
      "world records 2026",
      "general knowledge hindi",
      "how things work",
      "geography documentary",
      "map men",
      "history explained",
      "empire documentary",
      "war history documentary",
      "biography documentary"
    ],
    "name": "Education & Facts",
    "position": 24
  },
  {
    "createdAt": 1748000000025,
    "enabled": true,
    "icon": "🔥",
    "id": "epic_fails_wins",
    "keywords": [
      "fail compilation 2026",
      "epic win compilation",
      "people are awesome 2026",
      "failarmy best",
      "instant karma compilation",
      "lucky people compilation",
      "close call moments",
      "viral video 2026",
      "best moments caught on camera",
      "perfectly cut screams",
      "unexpected moments compilation",
      "satisfying video compilation",
      "oddly satisfying",
      "unbelievable moments"
    ],
    "name": "Fails, Wins & Viral",
    "position": 25
  },
  {
    "createdAt": 1748000000026,
    "enabled": true,
    "icon": "🏙️",
    "id": "nashik_local",
    "keywords": [
      "nashik food vlog",
      "nashik travel 2026",
      "nashik restaurant review",
      "pune food vlog",
      "maharashtra travel vlog",
      "india village life vlog",
      "rural india documentary",
      "nagpur vlog",
      "aurangabad travel",
      "kolhapur food vlog",
      "satara travel",
      "mahabaleshwar vlog",
      "lonavala vlog",
      "konkan coast vlog"
    ],
    "name": "Nashik & Local India",
    "position": 26
  },
  {
    "createdAt": 1748000000027,
    "enabled": true,
    "icon": "🎧",
    "id": "asmr_relaxation",
    "keywords": [
      "asmr sleep no talking",
      "asmr eating sounds",
      "asmr tapping scratching",
      "rain sounds for sleep 10 hours",
      "white noise sleep",
      "lofi music study",
      "study with me",
      "coffee shop ambience",
      "sleep meditation guided",
      "binaural beats focus",
      "dark screen sleep sounds",
      "library ambience",
      "cabin ambience rain",
      "train ambience sleep",
      "brown noise sleep"
    ],
    "name": "ASMR & Relaxation",
    "position": 27
  },
  {
    "createdAt": 1748000000028,
    "enabled": true,
    "icon": "🍳",
    "id": "drinks_recipes",
    "keywords": [
      "recipe hindi easy",
      "indian recipe",
      "biryani recipe authentic",
      "paneer recipe",
      "dal recipe",
      "roti recipe",
      "south indian recipe",
      "korean recipe at home",
      "japanese recipe easy",
      "italian pasta recipe",
      "pizza recipe homemade",
      "thai curry recipe",
      "chinese recipe at home",
      "bread baking",
      "sourdough bread",
      "cake recipe easy",
      "dessert recipe",
      "cocktail recipe",
      "coffee recipe latte",
      "cold brew coffee",
      "smoothie recipe healthy",
      "meal prep weekly",
      "one pot recipe",
      "vegan recipe easy",
      "keto recipe",
      "high protein meal prep",
      "Gordon Ramsay recipe",
      "Joshua Weissman recipe"
    ],
    "name": "Recipes & Cooking",
    "position": 28
  },
  {
    "createdAt": 1748000000029,
    "enabled": true,
    "icon": "👗",
    "id": "fashion_lifestyle",
    "keywords": [
      "fashion haul india",
      "outfit ideas men india",
      "get ready with me",
      "budget fashion india",
      "streetwear outfit",
      "luxury lifestyle vlog",
      "skincare routine",
      "grooming tips men",
      "perfume review",
      "sneaker review",
      "watch collection",
      "daily routine vlog",
      "morning routine productive",
      "minimalist lifestyle",
      "aesthetic vlog"
    ],
    "name": "Fashion & Lifestyle",
    "position": 29
  },
  {
    "createdAt": 1748100000000,
    "enabled": true,
    "icon": "✈️",
    "id": "global_travel",
    "keywords": [
      "japan travel vlog 2026",
      "korea travel vlog",
      "europe travel vlog",
      "india travel vlog",
      "bali travel vlog",
      "thailand travel vlog",
      "vietnam travel vlog",
      "italy travel vlog",
      "turkey travel vlog",
      "morocco travel vlog",
      "iceland travel vlog",
      "kashmir travel vlog",
      "ladakh travel vlog",
      "kerala travel vlog",
      "himachal travel vlog",
      "northeast india travel",
      "rajasthan travel",
      "andaman travel vlog",
      "solo travel vlog",
      "budget travel tips",
      "digital nomad vlog",
      "van life vlog",
      "cheapest countries travel",
      "hidden gems destination 2026",
      "travel documentary 4k",
      "cruise ship tour"
    ],
    "name": "Global Travel Vlogs",
    "position": 30
  },
  {
    "createdAt": 1748000000030,
    "enabled": true,
    "icon": "📌",
    "id": "india_attractions",
    "keywords": [
      "Statue of Unity Kevadia",
      "Ram Mandir Ayodhya",
      "Kashi Vishwanath Corridor",
      "Mahakal Lok Ujjain",
      "Imagicaa Theme Park",
      "Wonderla Hyderabad",
      "Ramoji Film City",
      "Golden Temple Amritsar",
      "Atal Tunnel Rohtang",
      "Gulmarg Gondola Kashmir",
      "Chenab Bridge Kashmir",
      "Gorewada Zoo Safari Nagpur",
      "Ranthambore Tiger Safari",
      "Tadoba Tiger Safari",
      "Gir National Park Lion Safari",
      "Kerala Backwaters Alleppey",
      "Sundarbans Boat Safari",
      "Nilgiri Mountain Railway Ooty",
      "Dal Lake Shikara Srinagar",
      "Wagah Border Ceremony"
    ],
    "name": "India Must-Visit",
    "position": 31
  },
  {
    "createdAt": 1748000000031,
    "enabled": true,
    "icon": "🎨",
    "id": "art_creative",
    "keywords": [
      "digital art timelapse",
      "oil painting tutorial",
      "watercolor painting",
      "street art mural",
      "calligraphy satisfying",
      "sculpture making",
      "animation process",
      "concept art tutorial",
      "photography tips",
      "cinematic filmmaking tutorial",
      "color grading tutorial",
      "drone cinematography",
      "film grain aesthetic",
      "album cover design",
      "graphic design process",
      "Blender 3D tutorial",
      "VFX breakdown",
      "CGI making of"
    ],
    "name": "Art & Creative",
    "position": 32
  },
  {
    "createdAt": 1748000000032,
    "enabled": true,
    "icon": "🧠",
    "id": "deep_docs",
    "keywords": [
      "best documentary 2026",
      "society documentary",
      "poverty documentary",
      "inequality documentary",
      "north korea documentary",
      "prison documentary",
      "addiction documentary",
      "cult documentary",
      "technology documentary",
      "internet documentary",
      "social media documentary",
      "food industry documentary",
      "ocean pollution documentary",
      "human trafficking documentary",
      "migration documentary",
      "healthcare documentary",
      "education system documentary",
      "future of humanity",
      "civilization documentary",
      "DW documentary english"
    ],
    "name": "Deep Documentaries",
    "position": 33
  },
  {
    "createdAt": 1748000000033,
    "enabled": true,
    "icon": "⚡",
    "id": "mega_engineering",
    "keywords": [
      "megastructure documentary",
      "mega factory documentary",
      "how it's made",
      "engineering marvel",
      "bridge construction",
      "tunnel construction",
      "dam construction documentary",
      "aircraft carrier documentary",
      "submarine documentary",
      "skyscraper construction timelapse",
      "train manufacturing",
      "ship building documentary",
      "rocket engine explained",
      "nuclear power plant documentary",
      "largest machine world",
      "boeing factory tour",
      "Tesla factory tour"
    ],
    "name": "Mega Engineering",
    "position": 34
  },
  {
    "createdAt": 1748000000034,
    "enabled": true,
    "icon": "🎹",
    "id": "music_performance",
    "keywords": [
      "live concert 4k",
      "street musician amazing",
      "piano cover popular song",
      "guitar cover",
      "drum cover",
      "one man band performance",
      "orchestra performance 4k",
      "beatbox champion",
      "acapella group",
      "music festival 4k",
      "jazz performance live",
      "blues performance live",
      "classical music performance",
      "indian classical music",
      "flamenco guitar performance",
      "busker amazing talent"
    ],
    "name": "Music Performances",
    "position": 35
  },
  {
    "createdAt": 1748000000035,
    "enabled": true,
    "icon": "💻",
    "id": "coding_dev",
    "keywords": [
      "programming tutorial 2026",
      "web development 2026",
      "python project tutorial",
      "javascript project",
      "react tutorial 2026",
      "build app from scratch",
      "full stack project",
      "coding challenge",
      "system design interview",
      "tech interview preparation",
      "freelancing developer",
      "SaaS build tutorial",
      "startup tech stack",
      "devops tutorial",
      "linux tutorial",
      "cybersecurity tutorial",
      "ethical hacking",
      "bug bounty"
    ],
    "name": "Coding & Dev",
    "position": 36
  },
  {
    "id": "kids_family",
    "name": "Kids & Family",
    "icon": "👨‍👩‍👧‍👦",
    "position": 37,
    "enabled": true,
    "createdAt": 1748100000001,
    "keywords": [
      "family vlog india",
      "kids rhymes hindi",
      "cartoon hindi",
      "panchatantra stories",
      "fun challenges for family",
      "indoor games for kids",
      "theme park vlog",
      "magic show",
      "toy unboxing"
    ]
  },
  {
    "id": "agriculture_farming",
    "name": "Agriculture & Farming",
    "icon": "🚜",
    "position": 38,
    "enabled": true,
    "createdAt": 1748100000002,
    "keywords": [
      "farming india",
      "tractor video",
      "modern agriculture",
      "agriculture machinery",
      "dairy farming india",
      "poultry farming hindi",
      "organic farming hindi",
      "village farming"
    ]
  },
  {
    "id": "photography_art",
    "name": "Photography & Art",
    "icon": "📸",
    "position": 39,
    "enabled": true,
    "createdAt": 1748100000003,
    "keywords": [
      "mobile photography tips",
      "video editing tutorial hindi",
      "cinematic b-roll",
      "origami tutorial",
      "drawing for beginners",
      "watercolor painting",
      "resin art",
      "mandala art"
    ]
  },
  {
    "id": "gardening_plants",
    "name": "Gardening & Plants",
    "icon": "🪴",
    "position": 40,
    "enabled": true,
    "createdAt": 1748100000004,
    "keywords": [
      "home gardening india",
      "indoor plants care",
      "balcony garden ideas",
      "terrace farming",
      "growing vegetables at home",
      "bonsai tree care",
      "succulents care"
    ]
  },
  {
    "id": "real_estate_luxury",
    "name": "Real Estate & Luxury",
    "icon": "🏰",
    "position": 41,
    "enabled": true,
    "createdAt": 1748100000005,
    "keywords": [
      "luxury home tour",
      "real estate india",
      "low budget house design",
      "billionaires lifestyle",
      "expensive cars",
      "luxury watches",
      "private jet tour",
      "mega mansion tour"
    ]
  },
  {
    "id": "dance_music_arts",
    "name": "Dance & Choreography",
    "icon": "💃",
    "position": 42,
    "enabled": true,
    "createdAt": 1748100000006,
    "keywords": [
      "dance choreography hindi",
      "wedding dance performance",
      "classical dance india",
      "hip hop dance tutorial",
      "bollywood dance cover",
      "couple dance performance"
    ]
  },
  {
    "id": "pets_care",
    "name": "Pets & Animal Care",
    "icon": "🐶",
    "position": 43,
    "enabled": true,
    "createdAt": 1748100000007,
    "keywords": [
      "dog training hindi",
      "cat care tips",
      "aquarium setup",
      "speaking parrot",
      "exotic pets",
      "puppy care guide",
      "best dog breeds india"
    ]
  },
  {
    "id": "history_mythology",
    "name": "History & Mythology",
    "icon": "📜",
    "position": 44,
    "enabled": true,
    "createdAt": 1748100000008,
    "keywords": [
      "indian history hindi",
      "ramayana facts",
      "mystery of temples india",
      "ancient india",
      "mahabharat stories",
      "historical monuments india",
      "world history documentary"
    ]
  },
  {
    "id": "health_remedies",
    "name": "Health Remedies & Diet",
    "icon": "🥗",
    "position": 45,
    "enabled": true,
    "createdAt": 1748100000009,
    "keywords": [
      "healthy recipes hindi",
      "glowing skin diet",
      "home remedies hindi",
      "immunity booster drink",
      "detox water benefits",
      "superfoods for health",
      "hair fall remedies hindi"
    ]
  }
];
